version: "3"
services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - "4000:3000"
    depends_on:
      - database
  database:
    container_name: postgres
    image: postgres:12.12-alpine
    env_file: .env
    restart: on-failure
    volumes:
      - ./pg-data:/data/postgres
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
